import { Connection, PublicKey } from "@solana/web3.js";
import { AnchorProvider, Program } from "@coral-xyz/anchor";
import { AnchorWallet } from "@solana/wallet-adapter-react";
import type { Idl } from "@coral-xyz/anchor";

// ── Replace this with your deployed program ID after `anchor build && anchor deploy` ──
export const PROGRAM_ID = new PublicKey(
  "4qQrJUhbTubHVaiStBafsHmNtY2RWy3F7x8v91VSYXdW"
);

// Switch to devnet RPC for a real devnet deployment
export const NETWORK_URL =
  process.env.NEXT_PUBLIC_SOLANA_RPC_URL ?? "http://127.0.0.1:8899";

export const NETWORK_LABEL =
  process.env.NEXT_PUBLIC_NETWORK_LABEL ?? "localnet";

/** Build an AnchorProvider + Program from a connected wallet. */
export function getProgram(wallet: AnchorWallet, connection: Connection) {
  const provider = new AnchorProvider(connection, wallet, {
    preflightCommitment: "confirmed",
    commitment: "confirmed",
  });

  // IDL is imported from the idl/ folder (generated by `anchor build`).
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const idl = require("../../idl/tip_jar.json") as Idl;

  return new Program(idl, provider);
}

/** Read-only provider for fetching account data without a wallet. */
export function getReadonlyProvider(connection: Connection) {
  return new AnchorProvider(
    connection,
    {
      publicKey: PublicKey.default,
      signTransaction: async (tx) => tx,
      signAllTransactions: async (txs) => txs,
    },
    { commitment: "confirmed" }
  );
}

export function getReadonlyProgram(connection: Connection) {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const idl = require("../../idl/tip_jar.json") as Idl;
  const provider = getReadonlyProvider(connection);
  return new Program(idl, provider);
}
